defaults:
  - _self_
  - payloads: cargo
  - optimisation_guide: guide

run_name: ${optimiser}_${scorer_method}
hydra:
  run:
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}_${run_name}

url: http://127.0.0.1:7860
webui: a1111  # or "forge"

wildcards_dir: path/to/wildcards/folder

model_paths:  # Use a list to specify model paths (first 3 are treated as abc)
  - path/to/model_a.safetensors
  - path/to/model_b.safetensors
  - path/to/model_c.safetensors
  - path/to/model_n.safetensors

device: cpu # specify device to merge on (cpu, cuda)
threads: 4

merge_mode: weighted_sum # specify merge method https://github.com/ljleb/sd-mecha/blob/main/sd_mecha/merge_methods/__init__.py
model_arch: sdxl  # specify model architecture (sd1, sdxl, sd3)

optimiser: bayes                 # tpe
bounds_transformer: False        # bayes only
latin_hypercube_sampling: False  # bayes only
guided_optimisation: False
batch_size: 1
init_points: 1
n_iters: 1

save_imgs: False
img_average_type: arithmetic # geometric, arithmetic, quadratic

# scorer by type:
# Prompt-Image Alignment:               blip, clip
# Aesthetic:                            chad, laion
# Hybrid(PIA + AES):                    ir, hpsv2, pick
# Anime/Illustration:                   shadow, cafe, wdaes
# Misc:                                 manual, noai, iqa
#
# !!!! IQA ARE NOT IMPLEMENTED YET !!!!
#
# Notes:
# 1) recomended tested safe setup is [laion, chad, clip, blip, ir] with weights 0.5, 0.5, 1, 1, 1

scorer_method: [clip, blip, laion, chad, ir]
scorer_average_type: arithmetic # geometric, arithmetic, quadratic
scorer_weight:
  #blip: 0.5
  #chad: 2
  # example above, default is 1
scorer_default_device: cpu # cuda
scorer_device:
  #blip: cpu
  #chad: cuda
  # example above, default is scorer default device
scorer_model_dir: path/to/scorer/models/folder
scorer_alt_location:
  #blip:
    #model_name: scorer.pth
    #model_dir: path/to/scorer/scorer.pth
  #chad:
    #model_name: scorer.pt
    #model_dir: path/to/scorer/scorer.pt
  # example above, default downloads them in the scorer_model_dir(this option is here if you already have them downloaded somewhere else)
scorer_print_individual: False

save_best: True
best_precision: 16 # 32

visualizations:
  scatter_plot: True # not implemented
  unet_diagram: True
  convergence_plot: True
  heatmap: True # not implemented
