defaults:
  - _self_
  - payloads: cargo
  - optimisation_guide: guide

run_name: ${optimiser}_${scorer_method}
hydra:
  run:
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}_${run_name}

url: http://127.0.0.1:7860
device: cpu
work_device: cpu
threads: 1

wildcards_dir: path/to/wildcards/folder
scorer_model_dir: path/to/scorer/models/folder

model_a: path/to/model_a/file
model_b: path/to/model_b/file
model_c: path/to/model_c/file
merge_mode: weighted_sum  # see https://github.com/s1dlx/meh/wiki
prune: False
weights_clip: False
rebasin: False
rebasin_iterations: 1

optimiser: bayes                 # tpe
bounds_transformer: False        # bayes only
latin_hypercube_sampling: False  # bayes only
guided_optimisation: False
batch_size: 1
init_points: 1
n_iters: 1

save_imgs: False
img_average_type: arithmetic # arithmetic, geometric, exponential

# scorer by type:
# Prompt-Image Alignment:               blip, clip
# Aesthetic:                            chad, laion
# Hybrid(PIA + AES):                    ir, hpsv2, pick
# Anime/Illustration:                   shadow, cafe, wdaes
# Misc:                                 manual, noai, iqa
#
# !!!! NOAI AND IQA ARE NOT IMPLEMENTED YET !!!!
#
# Notes:
# 1) recomended tested safe setup is [laion, chad, clip, blip, ir] with weights 0.5, 0.5, 1, 1, 1

scorer_method: [clip, blip, laion, chad, ir]
scorer_average_type: arithmetic # arithmetic, geometric, exponential
scorer_weights:
  "blip": 1
  "clip": 1
  "chad": 0.5
  "laion": 0.5
  "ir": 1
  "pick": 0
  "hpsv2": 0
  "shadow": 0
  "cafe": 0
  "wdaes": 0
  "noai": 0
  "iqa": 0
  "manual": 0
scorer_device:
  "blip": cpu # cuda
  "clip": cpu # cuda
  "chad": cpu # cuda
  "laion": cpu # cuda
  "ir": cpu # cuda
  "pick": cpu # cuda
  "hpsv2": cpu # cuda
  "shadow": cpu # cuda
  "cafe": cpu # cuda
  "wdaes": cpu # cuda
  "noai": cpu # cuda
  "iqa": cpu # cuda
scorer_print_individual: False


save_best: False
best_format: safetensors # ckpt
best_precision: 16 # 32

draw_unet_weights: False
draw_unet_base_alpha: False
